### ISSUE TITLE
Cross-platform support with pre-compiled binaries?

### ISSUE THREAD

**Issue by Alexander-Barth** [kouketsu/GSW.jl#1]
While I use only Linux myself, several students and co-workers use Windows and Mac OS X. Would you consider to add support of these other platforms where a C-compiler is not (easily)  available? Are you aware of the work of @ax1ine ? He has setup some code to generate precompiled binaries. Maybe it would be useful to join forces.

**Comment by truedichotomy** [comment]
The current version works well on my macOS machine, but I have a student who is running Windows and he is encountering some issues installing GSW.jl. Gives a recompile error saying the package is not installed properly. Any help on this would be appreciated!

**Comment by Alexander-Barth** [comment]
I just tried making the pre-compiled library with `BinaryBuilder.jl`:

```julia
using BinaryBuilder
BinaryBuilder.run_wizard()
```
As URL I used `https://github.com/TEOS-10/GSW-C/archive/d392e91cb63341f543ed1609c4eff613055ab3cb.zip` (same commit as the julia wrapper).

As build script I used:
```
cd $WORKSPACE/srcdir
cd GSW-C-d392e91cb63341f543ed1609c4eff613055ab3cb/
$CC $CFLAGS -fPIC -c -O3 -Wall  gsw_oceanographic_toolbox.c gsw_saar.c

if [ $target = "x86_64-w64-mingw32" ] || [ $target = "i686-w64-mingw32" ] || [ $target = "x86_64-apple-darwin14" ]; then
  LD=$CC
elif [ $target = "x86_64-unknown-freebsd11.1" ]; then
  LD=ld
fi

$LD $LDFLAGS -fPIC -shared -o libgswteos-10.$dlext gsw_oceanographic_toolbox.o gsw_saar.o -lm
cp libgswteos-10.$dlext $prefix
exit


```

The GNUmakefile of GSW uses always gcc which causes problems on MacOS. `$CC` is clang on MacOS and FreeBSD but I need to use `ld` as linker (otherwise I get an error about missing `-lgcc_s` library). 


I would be good to have the binaries in https://github.com/JuliaPackaging/Yggdrasil .

**Comment by kouketsu** [comment]
Thanks, @Alexander-Barth.
As I have been considering I should provide binaries for multi-platforms with BinaryBuilder.jl, with your script (https://github.com/kouketsu/GSW.jl/issues/1#issuecomment-556395563), I'm happy I can update my package at this time.

As I noticed [@ax1ine](https://github.com/ax1ine/GSW.jl) work, I will comment on his repository.
Thank you for your constructive suggestion (https://github.com/kouketsu/GSW.jl/issues/1#issue-524874327).

**Comment by Alexander-Barth** [comment]
Thanks a lot for addressing this issue so quickly!

**Comment by truedichotomy** [comment]
Thank you! When I tried to update or reinstall GSW.jl, it keeps on pointing me to the 0.1.0 release. I can't seem to grab version 1.0.0 using Pkg for some reason. I tried both `add https://github.com/kouketsu/GSW.jl` and `Pkg.add(PackageSpec(url="https://github.com/kouketsu/GSW.jl", rev="master"))`. Thanks.

**Comment by kouketsu** [comment]
Sorry, I forgot to update the version number (only the version number, I think the package will work well). 

I fixed. Thanks
